import React from 'react'
import Head from "next/head";

const header = () => {
  return (
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />

    {/* <!-- slider stylesheet --> */}
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css"
    />

    {/* <!-- bootstrap core css --> */}
    <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />

    {/* <!-- fonts style --> */}
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,700&display=swap"
      rel="stylesheet"
    />
    {/* <!-- Custom styles for this template --> */}
    <link href="/css/style.css" rel="stylesheet" />
    {/* <!-- responsive style --> */}
    <link href="css/responsive.css" rel="stylesheet" />

    <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.js"></script>
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js"
    ></script>
    <script src=""></script>
    <script src="js/tool.js"></script>
  </Head>
  )
}

export default header